- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1038/s41567-021-01335-8
  authors:
  - Aditi Chakrabarti
  - Thomas C. T. Michaels
  - Sifan Yin
  - Eric D. Sun
  - L. Mahadevan

- id: doi:10.1093/bioinformatics/btae253
  authors:
  - Eric D. Sun
  - Rong Ma
  - James Zou

- id: doi:10.1016/j.cub.2020.05.052
  authors:
  - Thomas Lenormand
  - Frederic Fyon
  - Eric D. Sun
  - Denis Roze

- id: doi:10.61373/gp025k.0065
  - image: https://genomicpress.kglmeridian.com/view/journals/genpsych/aop/article-10.61373-gp025k.0065/images/full-gp025k0065f2.jpg

- id: doi:10.1038/s41586-024-08334-8
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-024-08334-8/MediaObjects/41586_2024_8334_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41586-024-07972-2
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-024-07972-2/MediaObjects/41586_2024_7972_Fig2_HTML.png?as=webp

- id: doi:10.1038/s43587-024-00594-3
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43587-024-00594-3/MediaObjects/43587_2024_594_Fig3_HTML.png?as=webp

- id: doi:10.1073/pnas.2313719121
  - image: https://www.pnas.org/cms/10.1073/pnas.2313719121/asset/1b433787-1c3d-41ee-a205-5a80ec704726/assets/images/large/pnas.2313719121fig01.jpg
  
- id: doi:10.1038/s41592-024-02184-y
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41592-024-02184-y/MediaObjects/41592_2024_2184_Fig1_HTML.png?as=webp

- id: doi:10.1093/bioinformatics/btae253
  - image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/40/Supplement_1/10.1093_bioinformatics_btae253/1/m_btae253f1.jpeg?Expires=1754371165&Signature=yJCF9u~VTJlYKilfPDmJGouLSVdlf9AKUlKuws6t~eHCQ71PJt71EZ6Bh3oimdIWWKEzYeOtoG4U2nxYZ8TMoC8K2odCNjVLExwRT9hs0434UYbgXSlqj~xl7dOU8EBUdPHkkvWWZPj96WetcRXKpykVGuCOIhCnU75~TZmjO2L42zB4ego6GpFbYcit8yhigY17FdjhJgckwGdsmUKt7S9UxL3ecl3vcUSI7DAk0t3J0h6P9kGODjR1qLbKIzM4TBNmkRKFCJ0Ywf7og9~S1B7oRxyi3BpYK8jZj4qGmjMDmd~4MT8aZM6p~unNYpggeN50Cw3r8qasFs~POqpiiw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1038/s43587-023-00449-3
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43587-023-00449-3/MediaObjects/43587_2023_449_Fig1_HTML.png?as=webp

- id: doi:10.18632/aging.203660
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-023-36492-2/MediaObjects/41467_2023_36492_Fig1_HTML.png?

- id: doi:10.1038/s43588-022-00380-4
  - image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs43588-022-00380-4/MediaObjects/43588_2022_380_Fig1_HTML.png?

- id: doi:10.1038/s43587-022-00335-4
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43587-022-00335-4/MediaObjects/43587_2022_335_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41567-021-01335-8
  - image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41567-021-01335-8/MediaObjects/41567_2021_1335_Fig1_HTML.png?as=webp

- id: doi:10.1167/jov.21.11.15
  - image: https://arvo.silverchair-cdn.com/arvo/content_public/journal/jov/938563/m_i1534-7362-21-11-15-f1_1634893875.69097.png?Expires=1753798090&Signature=DEhDz1OwPyYQyM1NbbfEQs-FdXoPe1BDDDuvGtz2omCrm0e6YKY-7hxKxky9bsuY~dB1Z7fOGlEDhW-FxpA2D7m-FEQvl0lIE~d6j~FHkZ57J74NUShwsH8teRoGY-Cbho3tQ7JJBLVwVKWW~y0t9jpS6i7PNsFIrccGagpr8-CeGk1aht61MJwSNV7avOpND0FbrXrLWN9CCGHM4061njRGvI8MMeTPKSINLlzlg2Cy4Cpg74xGAb5qSSurzwbUvBs~ruq5Swgh3sDw0U-TlouUZsiT8G5IrMnAXdm0-4gl9RAmxA8dlwFOyuK0D0u1rer6CDbpC-dkRJAvjMyQIg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA


- id: doi:10.18632/aging.203660
  - image: https://www.aging-us.com/issue/v13i20/cover/medium

- id: doi:10.1073/pnas.2006375117
  - image: https://www.pnas.org/cms/10.1073/pnas.2006375117/asset/aa64ff89-7183-41da-a592-a1ade259727d/assets/images/large/pnas.2006375117fig01.jpg

- id: doi:10.1016/j.cub.2020.05.052
  - image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982220307399-gr1.jpg
